import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./components/Navbar";
import { Toaster } from "./components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          `font-sans ${inter.variable}`,
          "bg-background text-foreground",
        )}
      >
        <TRPCReactProvider headers={headers()}>
          <Navbar />
          <main className="mx-4 my-8 min-h-full lg:mx-8">
            {children}
            <Toaster />
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
